import { Product, Review, CartItem, Order, User } from '@/types';

const PLACEHOLDER_IMAGES = {
  'crop-top-1': 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=600&q=80',
  'crop-top-2': 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&q=80',
  'crop-top-3': 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
  'crop-top-4': 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=600&q=80',
  'sweatpants-1': 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&q=80',
  'sweatpants-2': 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
  'sweatpants-3': 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80',
  'hoodie-1': 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
  'hoodie-2': 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80',
  'hoodie-3': 'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&q=80',
  'shirt-1': 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
  'shirt-2': 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
  'shirt-3': 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
  'shirt-4': 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
};

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Heritage Crop Top',
    slug: 'heritage-crop-top',
    description: 'Inspired by ancient Kente patterns, this premium crop top features intricate embroidery along the neckline. Crafted from organic cotton blend.',
    price: 149,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-1'],
    images: [
      PLACEHOLDER_IMAGES['crop-top-1'],
      PLACEHOLDER_IMAGES['crop-top-2'],
      PLACEHOLDER_IMAGES['crop-top-3'],
    ],
    colors: [
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Gold', hex: '#D4A574' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: false },
      { size: 'XL', available: true },
    ],
    stock: 24,
    featured: true,
    isNew: true,
    variants: [],
    rating: 4.8,
    reviewCount: 34,
    tags: ['african', 'embroidery', 'organic'],
  },
  {
    id: '2',
    name: 'Adinkra Crop',
    slug: 'adinkra-crop',
    description: 'Adorned with Adinkra symbols representing wisdom and unity. This piece is a wearable canvas of African philosophy and modern minimalism.',
    price: 179,
    originalPrice: 220,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-2'],
    images: [
      PLACEHOLDER_IMAGES['crop-top-2'],
      PLACEHOLDER_IMAGES['crop-top-1'],
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Cream', hex: '#F5F1EB' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: false },
      { size: 'L', available: true },
    ],
    stock: 12,
    featured: true,
    isNew: false,
    variants: [],
    rating: 4.9,
    reviewCount: 18,
    tags: ['adinkra', 'cultural', 'limited'],
  },
  {
    id: '3',
    name: 'Crown Emblem Crop',
    slug: 'crown-emblem-crop',
    description: 'The crown — symbol of royalty and excellence — embroidered in metallic gold thread on our signature relaxed fit crop top.',
    price: 139,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-3'],
    images: [PLACEHOLDER_IMAGES['crop-top-3']],
    colors: [
      { name: 'Navy', hex: '#1A1A2E' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: false },
    ],
    stock: 31,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.7,
    reviewCount: 22,
    tags: ['crown', 'royal', 'gold-embroidery'],
  },
  {
    id: '4',
    name: 'Sankofa Crop Top',
    slug: 'sankofa-crop-top',
    description: 'Sankofa — "go back and get it." This piece honors the past while looking forward, featuring a delicate back motif of the iconic bird symbol.',
    price: 159,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-4'],
    images: [PLACEHOLDER_IMAGES['crop-top-4']],
    colors: [
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Gold', hex: '#D4A574' },
    ],
    sizes: [
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
    ],
    stock: 8,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.6,
    reviewCount: 11,
    tags: ['sankofa', 'ghana', 'symbolic'],
  },
  {
    id: '5',
    name: 'Minimalist Crop',
    slug: 'minimalist-crop',
    description: 'Clean lines, premium fabric, subtle gold hem detail. Sometimes less is everything.',
    price: 119,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-1'],
    images: [PLACEHOLDER_IMAGES['crop-top-1']],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
      { size: 'XXL', available: true },
    ],
    stock: 50,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.5,
    reviewCount: 45,
    tags: ['minimal', 'versatile', 'everyday'],
  },
  {
    id: '6',
    name: 'Ankara Fusion Crop',
    slug: 'ankara-fusion-crop',
    description: 'A fusion of Ankara print accents with contemporary silhouette. Bold, proud, unapologetically African.',
    price: 169,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-2'],
    images: [PLACEHOLDER_IMAGES['crop-top-2']],
    colors: [
      { name: 'Multi', hex: '#E8B88A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: false },
      { size: 'M', available: true },
      { size: 'L', available: true },
    ],
    stock: 15,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.7,
    reviewCount: 28,
    tags: ['ankara', 'print', 'bold'],
  },
  {
    id: '7',
    name: 'Heritage Sweatpants',
    slug: 'heritage-sweatpants',
    description: 'Ultra-soft French terry lounge sweatpants with our signature crown motif embroidered at the hip. The pinnacle of luxury comfort.',
    price: 229,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-1'],
    images: [
      PLACEHOLDER_IMAGES['sweatpants-1'],
      PLACEHOLDER_IMAGES['sweatpants-2'],
    ],
    colors: [
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Cream', hex: '#F5F1EB' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    stock: 20,
    featured: true,
    isNew: true,
    variants: [],
    rating: 4.9,
    reviewCount: 52,
    tags: ['lounge', 'french-terry', 'crown'],
  },
  {
    id: '8',
    name: 'Kente Stripe Sweatpants',
    slug: 'kente-stripe-sweatpants',
    description: 'Inspired by the bold geometric patterns of Kente cloth, these premium sweatpants feature subtle woven stripe accents down the leg.',
    price: 249,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-2'],
    images: [PLACEHOLDER_IMAGES['sweatpants-2']],
    colors: [
      { name: 'Navy', hex: '#1A1A2E' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: [
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: false },
      { size: 'XL', available: true },
    ],
    stock: 16,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.8,
    reviewCount: 29,
    tags: ['kente', 'stripe', 'premium'],
  },
  {
    id: '9',
    name: 'Relaxed Fit Joggers',
    slug: 'relaxed-fit-joggers',
    description: 'Effortless style meets supreme comfort. Our relaxed fit joggers are tailored with tapered cuffs and a luxuriously soft interior.',
    price: 199,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-3'],
    images: [PLACEHOLDER_IMAGES['sweatpants-3']],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Cream', hex: '#F5F1EB' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
      { size: 'XXL', available: true },
    ],
    stock: 35,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.7,
    reviewCount: 63,
    tags: ['jogger', 'relaxed', 'versatile'],
  },
  {
    id: '10',
    name: 'Tribal Embroidered Joggers',
    slug: 'tribal-embroidered-joggers',
    description: 'Featuring intricate hand-guided embroidery down the leg inspired by West African textile traditions. Each pair is unique.',
    price: 279,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-1'],
    images: [PLACEHOLDER_IMAGES['sweatpants-1']],
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    sizes: [
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
    ],
    stock: 6,
    featured: true,
    isNew: false,
    variants: [],
    rating: 5.0,
    reviewCount: 14,
    tags: ['embroidery', 'tribal', 'limited-edition'],
  },
  {
    id: '11',
    name: 'Ivory Lounge Pants',
    slug: 'ivory-lounge-pants',
    description: 'Pure luxury in ivory. Wide-leg silhouette with a satin-finish waistband and subtle crown monogram at the ankle.',
    price: 219,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-2'],
    images: [PLACEHOLDER_IMAGES['sweatpants-2']],
    colors: [
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Gold', hex: '#D4A574' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: false },
      { size: 'L', available: true },
    ],
    stock: 18,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.6,
    reviewCount: 22,
    tags: ['wide-leg', 'ivory', 'luxury'],
  },
  {
    id: '12',
    name: 'Cultural Heritage Hoodie',
    slug: 'cultural-heritage-hoodie',
    description: 'Our flagship hoodie. Heavyweight French terry with a full-chest crown emblem in gold embroidery and African tribal sleeve detail.',
    price: 299,
    category: 'hoodies',
    image: PLACEHOLDER_IMAGES['hoodie-1'],
    images: [
      PLACEHOLDER_IMAGES['hoodie-1'],
      PLACEHOLDER_IMAGES['hoodie-2'],
      PLACEHOLDER_IMAGES['hoodie-3'],
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    stock: 22,
    featured: true,
    isNew: true,
    variants: [],
    rating: 4.9,
    reviewCount: 87,
    tags: ['flagship', 'heavyweight', 'gold-embroidery'],
  },
  {
    id: '13',
    name: 'Minimalist Pullover',
    slug: 'minimalist-pullover',
    description: 'Clean silhouette, premium materials. The minimalist pullover is designed for those who know that true luxury needs no embellishment.',
    price: 259,
    category: 'hoodies',
    image: PLACEHOLDER_IMAGES['hoodie-2'],
    images: [PLACEHOLDER_IMAGES['hoodie-2']],
    colors: [
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Black', hex: '#000000' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: false },
      { size: 'XL', available: true },
      { size: 'XXL', available: true },
    ],
    stock: 28,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.8,
    reviewCount: 41,
    tags: ['minimal', 'pullover', 'premium'],
  },
  {
    id: '14',
    name: 'Royal Oversized Hoodie',
    slug: 'royal-oversized-hoodie',
    description: 'Generous oversized silhouette with dropped shoulders and a heavyweight construction. The crown-print lining is our signature touch.',
    price: 329,
    originalPrice: 379,
    category: 'hoodies',
    image: PLACEHOLDER_IMAGES['hoodie-3'],
    images: [PLACEHOLDER_IMAGES['hoodie-3']],
    colors: [
      { name: 'Black', hex: '#000000' },
    ],
    sizes: [
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    stock: 10,
    featured: true,
    isNew: false,
    variants: [],
    rating: 4.9,
    reviewCount: 35,
    tags: ['oversized', 'royal', 'limited'],
  },
  {
    id: '15',
    name: 'Sankofa Hoodie',
    slug: 'sankofa-hoodie',
    description: 'The Sankofa bird in detailed embroidery across the back panel. Look forward, remember where you came from.',
    price: 289,
    category: 'hoodies',
    image: PLACEHOLDER_IMAGES['hoodie-1'],
    images: [PLACEHOLDER_IMAGES['hoodie-1']],
    colors: [
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Navy', hex: '#1A1A2E' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
    ],
    stock: 14,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.8,
    reviewCount: 19,
    tags: ['sankofa', 'back-embroidery', 'statement'],
  },
  {
    id: '16',
    name: 'Zip-Up Heritage Jacket',
    slug: 'zip-up-heritage-jacket',
    description: 'A zip-up hoodie with Adinkra-pattern woven panels at the elbows. Bridges athletic function with cultural expression.',
    price: 319,
    category: 'hoodies',
    image: PLACEHOLDER_IMAGES['hoodie-2'],
    images: [PLACEHOLDER_IMAGES['hoodie-2']],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Cream', hex: '#F5F1EB' },
    ],
    sizes: [
      { size: 'S', available: false },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    stock: 9,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.7,
    reviewCount: 26,
    tags: ['zip-up', 'adinkra', 'jacket'],
  },
  {
    id: '17',
    name: 'Gold Thread Crop',
    slug: 'gold-thread-crop',
    description: 'Gold metallic threading woven throughout the fabric creates a shimmering effect that catches the light beautifully.',
    price: 189,
    category: 'crop-tops',
    image: PLACEHOLDER_IMAGES['crop-top-4'],
    images: [PLACEHOLDER_IMAGES['crop-top-4']],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Navy', hex: '#1A1A2E' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
    ],
    stock: 7,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.9,
    reviewCount: 8,
    tags: ['gold-thread', 'shimmer', 'evening'],
  },
  {
    id: '18',
    name: 'Wide Leg Comfort Pants',
    slug: 'wide-leg-comfort-pants',
    description: 'Relaxed wide-leg joggers with premium waistband and side pockets. Comfort designed for the discerning individual.',
    price: 239,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-3'],
    images: [PLACEHOLDER_IMAGES['sweatpants-3']],
    colors: [
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Gold', hex: '#D4A574' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    stock: 25,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.6,
    reviewCount: 33,
    tags: ['wide-leg', 'comfort', 'everyday'],
  },
  {
    id: '19',
    name: 'Classic Hoodie',
    slug: 'classic-hoodie',
    description: 'The essential blac.cess hoodie. No frills, pure quality. Premium fleece with our discreet crown logo on the chest.',
    price: 249,
    category: 'hoodies',
    image: PLACEHOLDER_IMAGES['hoodie-3'],
    images: [PLACEHOLDER_IMAGES['hoodie-3']],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Cream', hex: '#F5F1EB' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
      { size: 'XXL', available: true },
    ],
    stock: 45,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.7,
    reviewCount: 112,
    tags: ['classic', 'essential', 'everyday'],
  },
  {
    id: '20',
    name: 'Tribe Sweatpants',
    slug: 'tribe-sweatpants',
    description: 'Premium heavyweight sweatpants with our TRIBE lettering in raised gold embroidery. A declaration, not just a garment.',
    price: 259,
    category: 'sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-1'],
    images: [PLACEHOLDER_IMAGES['sweatpants-1']],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: false },
    ],
    stock: 18,
    featured: true,
    isNew: true,
    variants: [],
    rating: 4.8,
    reviewCount: 41,
    tags: ['tribe', 'statement', 'premium'],
  },
  {
    id: '21',
    name: 'Heritage Tee',
    slug: 'heritage-tee',
    description: 'Heavyweight cotton tee with discreet crown embroidery on the chest. The everyday essential, refined.',
    price: 89,
    category: 'shirts',
    image: PLACEHOLDER_IMAGES['shirt-1'],
    images: [PLACEHOLDER_IMAGES['shirt-1'], PLACEHOLDER_IMAGES['shirt-2']],
    colors: [
      { name: 'Black',    hex: '#000000' },
      { name: 'Cream',    hex: '#F5F1EB' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S',  available: true },
      { size: 'M',  available: true },
      { size: 'L',  available: true },
      { size: 'XL', available: true },
    ],
    stock: 40,
    featured: true,
    isNew: true,
    variants: [],
    rating: 4.7,
    reviewCount: 58,
    tags: ['essential', 'tee', 'crown'],
  },
  {
    id: '22',
    name: 'Adinkra Button-Up',
    slug: 'adinkra-button-up',
    description: 'Linen-blend button-up with woven Adinkra symbols along the placket. Heritage at the seams, modern in cut.',
    price: 219,
    originalPrice: 260,
    category: 'shirts',
    image: PLACEHOLDER_IMAGES['shirt-2'],
    images: [PLACEHOLDER_IMAGES['shirt-2'], PLACEHOLDER_IMAGES['shirt-1']],
    colors: [
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: [
      { size: 'S',  available: true },
      { size: 'M',  available: true },
      { size: 'L',  available: false },
      { size: 'XL', available: true },
    ],
    stock: 14,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.9,
    reviewCount: 22,
    tags: ['adinkra', 'button-up', 'linen'],
  },
  {
    id: '23',
    name: 'Crown Emblem Shirt',
    slug: 'crown-emblem-shirt',
    description: 'Long-sleeve shirt with the crown emblem embroidered in metallic gold thread. A statement of quiet luxury.',
    price: 169,
    category: 'shirts',
    image: PLACEHOLDER_IMAGES['shirt-3'],
    images: [PLACEHOLDER_IMAGES['shirt-3']],
    colors: [
      { name: 'Black',    hex: '#000000' },
      { name: 'Navy',     hex: '#1A1A2E' },
      { name: 'Charcoal', hex: '#2A2A2A' },
    ],
    sizes: [
      { size: 'S',  available: true },
      { size: 'M',  available: true },
      { size: 'L',  available: true },
      { size: 'XL', available: true },
    ],
    stock: 22,
    featured: true,
    isNew: false,
    variants: [],
    rating: 4.8,
    reviewCount: 35,
    tags: ['long-sleeve', 'crown', 'embroidered'],
  },
  {
    id: '24',
    name: 'Kente Stripe Tee',
    slug: 'kente-stripe-tee',
    description: 'A short-sleeve tee with subtle Kente-inspired stripes woven across the chest. Heritage hidden in plain sight.',
    price: 109,
    category: 'shirts',
    image: PLACEHOLDER_IMAGES['shirt-4'],
    images: [PLACEHOLDER_IMAGES['shirt-4'], PLACEHOLDER_IMAGES['shirt-1']],
    colors: [
      { name: 'Cream', hex: '#F5F1EB' },
      { name: 'Black', hex: '#000000' },
      { name: 'Gold',  hex: '#D4A574' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S',  available: true },
      { size: 'M',  available: true },
      { size: 'L',  available: true },
    ],
    stock: 28,
    featured: false,
    isNew: true,
    variants: [],
    rating: 4.6,
    reviewCount: 19,
    tags: ['kente', 'stripe', 'tee'],
  },
  {
    id: '25',
    name: 'Ceremonial Overshirt',
    slug: 'ceremonial-overshirt',
    description: 'Heavyweight overshirt with ceremonial-pattern embroidery on the back yoke. Layer it open or wear it closed — equally striking.',
    price: 249,
    category: 'shirts',
    image: PLACEHOLDER_IMAGES['shirt-3'],
    images: [PLACEHOLDER_IMAGES['shirt-3'], PLACEHOLDER_IMAGES['shirt-2']],
    colors: [
      { name: 'Charcoal', hex: '#2A2A2A' },
      { name: 'Cream',    hex: '#F5F1EB' },
    ],
    sizes: [
      { size: 'M',  available: true },
      { size: 'L',  available: true },
      { size: 'XL', available: true },
    ],
    stock: 11,
    featured: false,
    isNew: false,
    variants: [],
    rating: 4.7,
    reviewCount: 14,
    tags: ['overshirt', 'ceremonial', 'layer'],
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    userName: 'Amara K.',
    userAvatar: 'https://i.pravatar.cc/40?img=1',
    rating: 5,
    title: 'Absolutely stunning',
    comment: 'The quality is incredible. The embroidery detail is so fine and the fabric feels luxurious. I get compliments every time I wear this.',
    verified: true,
    date: '2026-04-15',
  },
  {
    id: 'r2',
    productId: '1',
    userName: 'Zola M.',
    userAvatar: 'https://i.pravatar.cc/40?img=5',
    rating: 5,
    title: 'Worth every penny',
    comment: 'blac.cess truly delivers on their promise of luxury. The cultural details are done tastefully and with respect. Will be ordering more.',
    verified: true,
    date: '2026-04-02',
  },
  {
    id: 'r3',
    productId: '7',
    userName: 'Kemi A.',
    userAvatar: 'https://i.pravatar.cc/40?img=9',
    rating: 5,
    title: 'My most worn item',
    comment: 'These sweatpants are unreal. The softness, the fit, the crown detail — everything is perfect. I wear them daily.',
    verified: true,
    date: '2026-03-28',
  },
  {
    id: 'r4',
    productId: '12',
    userName: 'Ife B.',
    userAvatar: 'https://i.pravatar.cc/40?img=12',
    rating: 5,
    title: 'Flagship piece for a reason',
    comment: 'This hoodie is a statement. The gold embroidery is stunning, the weight is perfect, and the fit is exactly right. A masterpiece.',
    verified: true,
    date: '2026-04-20',
  },
];

export const mockCartItems: CartItem[] = [
  {
    id: 'ci1',
    productId: '1',
    name: 'Heritage Crop Top',
    image: PLACEHOLDER_IMAGES['crop-top-1'],
    price: 149,
    quantity: 1,
    color: 'Cream',
    size: 'S',
    category: 'crop-tops',
  },
  {
    id: 'ci2',
    productId: '7',
    name: 'Heritage Sweatpants',
    image: PLACEHOLDER_IMAGES['sweatpants-1'],
    price: 229,
    quantity: 1,
    color: 'Charcoal',
    size: 'M',
    category: 'sweatpants',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord1',
    orderNumber: 'BC-2026-1001',
    status: 'delivered',
    items: mockCartItems,
    address: {
      id: 'addr1',
      type: 'shipping',
      fullName: 'Test User',
      phone: '+1 555 0100',
      street: '123 Crown Street',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'United States',
      isDefault: true,
    },
    subtotal: 378,
    shipping: 0,
    tax: 30.24,
    total: 408.24,
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-04-05T14:00:00Z',
    trackingNumber: 'TRK-1234567890',
  },
  {
    id: 'ord2',
    orderNumber: 'BC-2026-1002',
    status: 'shipped',
    items: [mockCartItems[0]],
    address: {
      id: 'addr1',
      type: 'shipping',
      fullName: 'Test User',
      phone: '+1 555 0100',
      street: '123 Crown Street',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'United States',
      isDefault: true,
    },
    subtotal: 149,
    shipping: 12,
    tax: 11.92,
    total: 172.92,
    createdAt: '2026-04-18T09:00:00Z',
    updatedAt: '2026-04-19T11:00:00Z',
  },
];

export const mockUser: User = {
  id: 'u1',
  name: 'Amara Nwosu',
  email: 'amara@example.com',
  avatar: 'https://i.pravatar.cc/80?img=1',
  phone: '+1 555 0100',
};

export const getFeaturedProducts = (): Product[] =>
  mockProducts.filter((p) => p.featured).slice(0, 4);

export const getProductsByCategory = (category: string): Product[] =>
  mockProducts.filter((p) => p.category === category);

export const getProductById = (id: string): Product | undefined =>
  mockProducts.find((p) => p.id === id);

export const getRelatedProducts = (product: Product): Product[] =>
  mockProducts.filter((p) => p.category === product.category && p.id !== product.id).slice(0, 4);
